import Config

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure your database
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :revelo, Revelo.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "revelo_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :revelo, ReveloWeb.Endpoint,
  # use `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  # ## SSL Support
  #
  # In order to use HTTPS in development, a self-signed
  # certificate can be generated by running the following
  # Mix task:
  #
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "hUfCOzwW+9gfeqUyZfc18dkFP0BHWrhxDRL8lNTAbKQQC01NP3M/PWHEVnd/z0f7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:revelo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:revelo, ~w(--watch)]},
    storybook_tailwind: {Tailwind, :install_and_run, [:storybook, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
config :revelo, ReveloWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/revelo_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"storybook/.*(exs)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :revelo, dev_routes: true, token_signing_secret: "Ssj516I0uX6JqBiR4n1YWXPnr2eKJQXK"

# Path to install SaladUI components
config :salad_ui, components_path: Path.join(File.cwd!(), "lib/revelo_web/components")

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
