defmodule Revelo.Repo.Migrations.AddTypeOverrideColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:relationships) do
      add :type_override, :text
    end
  end

  def down do
    alter table(:relationships) do
      remove :type_override
    end
  end
end