defmodule Revelo.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variables, primary_key: false) do
      add :creator_id,
          references(:users, column: :id, name: "variables_creator_id_fkey", type: :uuid),
          null: false

      add :session_id,
          references(:sessions, column: :id, name: "variables_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :hidden?, :boolean, null: false
      add :is_key?, :boolean, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:variable_votes, primary_key: false) do
      add :voter_id,
          references(:users, column: :id, name: "variable_votes_voter_id_fkey", type: :uuid),
          primary_key: true,
          null: false

      add :variable_id,
          references(:variables,
            column: :id,
            name: "variable_votes_variable_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create table(:users, primary_key: false) do
      add :hashed_password, :text
      add :admin, :boolean
      add :email, :citext
      add :id, :uuid, null: false, primary_key: true
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:variable_votes, [:variable_id, :voter_id],
             name: "variable_votes_unique_vote_index"
           )

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
      add :id, :uuid, null: false, primary_key: true
      add :created_at, :utc_datetime_usec, null: false
    end

    create table(:sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :report, :text
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:variables, [:name, :session_id], name: "variables_unique_name_index")

    create table(:session_participants, primary_key: false) do
      add :participant_id,
          references(:users,
            column: :id,
            name: "session_participants_participant_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_participants_session_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :facilitator?, :boolean
    end

    create table(:relationships, primary_key: false) do
      add :dst_id,
          references(:variables, column: :id, name: "relationships_dst_id_fkey", type: :uuid),
          null: false

      add :src_id,
          references(:variables, column: :id, name: "relationships_src_id_fkey", type: :uuid),
          null: false

      add :session_id,
          references(:sessions, column: :id, name: "relationships_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :hidden?, :boolean, null: false
      add :description, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:relationships, [:src_id, :dst_id],
             name: "relationships_unique_relationship_index"
           )

    create table(:relationship_votes, primary_key: false) do
      add :voter_id,
          references(:users, column: :id, name: "relationship_votes_voter_id_fkey", type: :uuid),
          primary_key: true,
          null: false

      add :relationship_id,
          references(:relationships,
            column: :id,
            name: "relationship_votes_relationship_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :type, :text, null: false
    end

    create unique_index(:relationship_votes, [:relationship_id, :voter_id],
             name: "relationship_votes_unique_vote_index"
           )

    create table(:loops, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :display_order, :bigint
      add :story, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:loop_relationships, primary_key: false) do
      add :relationship_id,
          references(:relationships,
            column: :id,
            name: "loop_relationships_relationship_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :loop_id,
          references(:loops, column: :id, name: "loop_relationships_loop_id_fkey", type: :uuid),
          primary_key: true,
          null: false
    end

    create table(:context_docs, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "context_docs_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :include?, :boolean, null: false
      add :text, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:context_docs, "context_docs_session_id_fkey")

    drop table(:context_docs)

    drop constraint(:loop_relationships, "loop_relationships_loop_id_fkey")

    drop constraint(:loop_relationships, "loop_relationships_relationship_id_fkey")

    drop table(:loop_relationships)

    drop table(:loops)

    drop_if_exists unique_index(:relationship_votes, [:relationship_id, :voter_id],
                     name: "relationship_votes_unique_vote_index"
                   )

    drop constraint(:relationship_votes, "relationship_votes_relationship_id_fkey")

    drop constraint(:relationship_votes, "relationship_votes_voter_id_fkey")

    drop table(:relationship_votes)

    drop_if_exists unique_index(:relationships, [:src_id, :dst_id],
                     name: "relationships_unique_relationship_index"
                   )

    drop constraint(:relationships, "relationships_session_id_fkey")

    drop constraint(:relationships, "relationships_src_id_fkey")

    drop constraint(:relationships, "relationships_dst_id_fkey")

    drop table(:relationships)

    drop constraint(:session_participants, "session_participants_session_id_fkey")

    drop constraint(:session_participants, "session_participants_participant_id_fkey")

    drop table(:session_participants)

    drop_if_exists unique_index(:variables, [:name, :session_id],
                     name: "variables_unique_name_index"
                   )

    drop table(:sessions)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:variable_votes, [:variable_id, :voter_id],
                     name: "variable_votes_unique_vote_index"
                   )

    drop table(:users)

    drop constraint(:variable_votes, "variable_votes_variable_id_fkey")

    drop constraint(:variable_votes, "variable_votes_voter_id_fkey")

    drop table(:variable_votes)

    drop constraint(:variables, "variables_session_id_fkey")

    drop constraint(:variables, "variables_creator_id_fkey")

    drop table(:variables)
  end
end
