defmodule Revelo.Repo.Migrations.AddRelationshipHashToLoop do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:loops) do
      add :relationship_hash, :text
    end

    create unique_index(:loops, [:relationship_hash], name: "loops_relationship_hash_index")
  end

  def down do
    drop_if_exists unique_index(:loops, [:relationship_hash],
                     name: "loops_relationship_hash_index"
                   )

    alter table(:loops) do
      remove :relationship_hash
    end
  end
end
