defmodule Revelo.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variables, primary_key: false) do
      add :creator_id, :uuid, null: false

      add :session_id,
          references(:sessions, column: :id, name: "variables_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :included?, :boolean, null: false
      add :voi?, :boolean, null: false
      add :description, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:variable_votes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :voter_id, :uuid, null: false, primary_key: true

      add :variable_id,
          references(:variables,
            column: :id,
            name: "variable_votes_variable_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:variable_votes, [:variable_id, :voter_id],
             name: "variable_votes_unique_vote_index"
           )

    create table(:sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :report, :text
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:session_participants, primary_key: false) do
      add :user_id, :uuid, null: false, primary_key: true

      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_participants_session_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false
    end

    create table(:relationships, primary_key: false) do
      add :dst_id,
          references(:variables, column: :id, name: "relationships_dst_id_fkey", type: :uuid),
          null: false

      add :src_id,
          references(:variables, column: :id, name: "relationships_src_id_fkey", type: :uuid),
          null: false

      add :session_id,
          references(:sessions, column: :id, name: "relationships_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :description, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:relationship_votes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :voter_id, :uuid, null: false, primary_key: true

      add :relationship_id,
          references(:relationships,
            column: :id,
            name: "relationship_votes_relationship_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:relationship_votes, [:relationship_id, :voter_id],
             name: "relationship_votes_unique_vote_index"
           )

    create table(:loops, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :description, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:loop_votes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :voter_id, :uuid, null: false, primary_key: true

      add :loop_id, references(:loops, column: :id, name: "loop_votes_loop_id_fkey", type: :uuid),
        primary_key: true,
        null: false
    end

    create unique_index(:loop_votes, [:loop_id, :voter_id], name: "loop_votes_unique_vote_index")

    create table(:loop_relationships, primary_key: false) do
      add :relationship_id,
          references(:loops,
            column: :id,
            name: "loop_relationships_relationship_id_fkey",
            type: :uuid
          ),
          primary_key: true,
          null: false

      add :loop_id,
          references(:loops, column: :id, name: "loop_relationships_loop_id_fkey", type: :uuid),
          primary_key: true,
          null: false
    end

    create table(:context_docs, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "context_docs_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :include?, :boolean, null: false
      add :text, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:context_docs, "context_docs_session_id_fkey")

    drop table(:context_docs)

    drop constraint(:loop_relationships, "loop_relationships_loop_id_fkey")

    drop constraint(:loop_relationships, "loop_relationships_relationship_id_fkey")

    drop table(:loop_relationships)

    drop_if_exists unique_index(:loop_votes, [:loop_id, :voter_id],
                     name: "loop_votes_unique_vote_index"
                   )

    drop constraint(:loop_votes, "loop_votes_loop_id_fkey")

    drop table(:loop_votes)

    drop table(:loops)

    drop_if_exists unique_index(:relationship_votes, [:relationship_id, :voter_id],
                     name: "relationship_votes_unique_vote_index"
                   )

    drop constraint(:relationship_votes, "relationship_votes_relationship_id_fkey")

    drop table(:relationship_votes)

    drop constraint(:relationships, "relationships_session_id_fkey")

    drop constraint(:relationships, "relationships_src_id_fkey")

    drop constraint(:relationships, "relationships_dst_id_fkey")

    drop table(:relationships)

    drop constraint(:session_participants, "session_participants_session_id_fkey")

    drop table(:session_participants)

    drop table(:sessions)

    drop_if_exists unique_index(:variable_votes, [:variable_id, :voter_id],
                     name: "variable_votes_unique_vote_index"
                   )

    drop constraint(:variable_votes, "variable_votes_variable_id_fkey")

    drop table(:variable_votes)

    drop constraint(:variables, "variables_session_id_fkey")

    drop table(:variables)
  end
end