defmodule Revelo.Repo.Migrations.RemoveIdFromTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    WITH duplicate_tokens AS (
        SELECT jti
        FROM tokens
        GROUP BY jti
        HAVING COUNT(*) > 1
    ),
    revocation_tokens AS (
        SELECT DISTINCT ON (t.jti) t.id
        FROM tokens t
        JOIN duplicate_tokens d ON t.jti = d.jti
        WHERE t.purpose = 'revocation'
    ),
    other_tokens AS (
        SELECT t.*
        FROM tokens t
        JOIN duplicate_tokens d ON t.jti = d.jti
        WHERE t.id NOT IN (SELECT id FROM revocation_tokens)
    )
    DELETE FROM tokens
    WHERE id IN (SELECT id FROM other_tokens);
    """)

    drop constraint("tokens", "tokens_pkey")

    alter table(:tokens) do
      remove :id
    end

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (jti)")
  end

  def down do
    alter table(:tokens) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute("ALTER TABLE \"tokens\" DROP constraint tokens_pkey")

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (id, jti)")
  end
end
