defmodule Revelo.Repo.Migrations.AddSessionIdToLoopTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:loops) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "loops_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:loops, "loops_session_id_fkey")

    alter table(:loops) do
      remove :session_id
    end
  end
end
